<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="cara">
    <xacro:include filename="$(find cara)/xacro/materials.xacro"/>
    <xacro:property name="c_clamp_dist" value="0.31"/>

    <gazebo>
        <plugin name="object_controller" filename="libgazebo_ros_planar_move.so">
            <commandTopic>cmd_vel</commandTopic>
            <odometryTopic>odom</odometryTopic>
            <odometryFrame>odom</odometryFrame>
            <odometryRate>30.0</odometryRate>
            <robotBaseFrame>base_link</robotBaseFrame>
        </plugin>
    </gazebo>

    <xacro:macro name="stud" params="myname x y z parent">
        <link name="${myname}">
            <visual>
                <origin xyz="${x} ${y} ${z}" rpy="${pi/2} 0 0"/>
                <geometry>
                    <mesh filename="package://cara/models/stud.stl" scale="0.001 0.001 0.001"/>
                </geometry>
                <material name="bronze"/>
            </visual>
        </link>
        <joint name="${parent}_${myname}" type="fixed">
            <parent link="${parent}"/>
            <child link="${myname}"/>
        </joint>
    </xacro:macro>

    <xacro:macro name="wheel">
        <visual>
            <origin xyz="0.02 0 0" rpy="0 0 ${pi/2}"/>
            <geometry>
                <mesh filename="package://cara/models/wheel2.dae"/>
            </geometry>
        </visual>
        <inertial>
            <mass value="0.5"/>
            <inertia ixx="0.0" ixy="0.0" ixz="0.0" iyy="0.000001" iyz="0.0" izz="0.0"/>
        </inertial>
        <collision>
            <origin xyz="0.027 0 0.0" rpy="0 ${pi/2} 0"/>
            <geometry>
                <cylinder length="0.045" radius="0.08"/>
            </geometry>
        </collision>
    </xacro:macro>

    <!-- ======================================================= Base Link ====================================================================== -->
    <link name="base_link">
        <visual>
            <origin xyz="0.01 0 0" rpy="${pi/2} 0 0"/>
            <geometry>
                <mesh filename="package://cara/models/base.stl" scale="0.001 0.001 0.001"/>
            </geometry>
            <material name="transparent_acrylic"/>
        </visual>
        <inertial>
            <mass value="8"/>
            <inertia ixx="0.000231" ixy="0.0" ixz="0.0" iyy="0.000439" iyz="-0.000001" izz="0.999454"/>
        </inertial>
        <collision>
            <origin xyz="0 0 0.05" rpy="0 0 ${pi/4}"/>
            <geometry>
                <box size="0.52 0.52 0.11"/>
            </geometry>
        </collision>
        <collision>
            <origin xyz="0 0 0.07" rpy="0 0 0"/>
            <geometry>
                <cylinder length="0.205" radius=".07"/>
            </geometry>
        </collision>
    </link>

    <!-- =======================================================Wheel 1====================================================================== -->
    <link name="c_clamp_1">
        <visual>
            <origin xyz="${-c_clamp_dist} 0.05 0.09" rpy="${pi/2} 0 0"/>
            <geometry>
                <mesh filename="package://cara/models/c_clamp.stl" scale="0.001 0.001 0.001"/>
            </geometry>
            <material name="aluminium"/>
        </visual>
    </link>
    <joint name="base_c_clamp_1" type="fixed">
        <parent link="base_link"/>
        <child link="c_clamp_1"/>
    </joint>
    <link name="motor_1">
        <visual>
            <origin xyz="${-(c_clamp_dist-0.012)} 0 0.045" rpy="${pi/2} 0 ${pi/2}"/>
            <geometry>
                <mesh filename="package://cara/models/motor.stl" scale="0.001 0.001 0.001"/>
            </geometry>
            <material name="aluminium_dark"/>
        </visual>
    </link>
    <joint name="c_clamp_motor_1" type="fixed">
        <parent link="c_clamp_1"/>
        <child link="motor_1"/>
    </joint>
    <link name="shaft_1">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <mesh filename="package://cara/models/motor_shaft.stl" scale="0.001 0.001 0.001"/>
            </geometry>
            <material name="plastic"/>
        </visual>
    </link>
    <joint name="motor_shaft_1" type="continuous">
        <parent link="base_link"/>
        <child link="shaft_1"/>
        <axis xyz="1 0 0"/>
        <origin xyz="${-(c_clamp_dist+0.01)} 0 0.045" rpy="0 0 ${pi}"/>
    </joint>
    <link name="wheel_1">
        <xacro:wheel/>
    </link>
    <joint name="shaft_wheel_1" type="fixed">
        <parent link="shaft_1"/>
        <child link="wheel_1"/>
    </joint>
    <!-- =======================================================Wheel 2====================================================================== -->
    <link name="c_clamp_2">
        <visual>
            <origin xyz="0.05 ${c_clamp_dist} 0.09" rpy="${pi/2} 0 -${pi/2}"/>
            <geometry>
                <mesh filename="package://cara/models/c_clamp.stl" scale="0.001 0.001 0.001"/>
            </geometry>
            <material name="aluminium"/>
        </visual>
    </link>
    <joint name="base_c_clamp_2" type="fixed">
        <parent link="base_link"/>
        <child link="c_clamp_2"/>
    </joint>
    <link name="motor_2">
        <visual>
            <origin xyz="0 ${(c_clamp_dist-0.012)} 0.045" rpy="${pi/2} -${pi} 0"/>
            <geometry>
                <mesh filename="package://cara/models/motor.stl" scale="0.001 0.001 0.001"/>
            </geometry>
            <material name="aluminium_dark"/>
        </visual>
    </link>
    <joint name="c_clamp_motor_2" type="fixed">
        <parent link="c_clamp_2"/>
        <child link="motor_2"/>
    </joint>
    <link name="shaft_2">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <mesh filename="package://cara/models/motor_shaft.stl" scale="0.001 0.001 0.001"/>
            </geometry>
            <material name="plastic"/>
        </visual>
    </link>
    <joint name="motor_shaft_2" type="continuous">
        <parent link="base_link"/>
        <child link="shaft_2"/>
        <origin xyz="0 ${(c_clamp_dist+0.01)} 0.045" rpy="0 0 ${pi/2}"/>
    </joint>
    <link name="wheel_2">
        <xacro:wheel/>
    </link>
    <joint name="shaft_wheel_2" type="fixed">
        <parent link="shaft_2"/>
        <child link="wheel_2"/>
    </joint>
    <!-- =======================================================Wheel 3====================================================================== -->
    <link name="c_clamp_3">
        <visual>
            <origin xyz="${c_clamp_dist} -0.05 0.09" rpy="${pi/2} 0 ${pi}"/>
            <geometry>
                <mesh filename="package://cara/models/c_clamp.stl" scale="0.001 0.001 0.001"/>
            </geometry>
            <material name="aluminium"/>
        </visual>
    </link>
    <joint name="base_c_clamp_3" type="fixed">
        <parent link="base_link"/>
        <child link="c_clamp_3"/>
    </joint>
    <link name="motor_3">
        <visual>
            <origin xyz="${(c_clamp_dist-0.012)} 0 0.045" rpy="${pi/2} 0 -${pi/2}"/>
            <geometry>
                <mesh filename="package://cara/models/motor.stl" scale="0.001 0.001 0.001"/>
            </geometry>
            <material name="aluminium_dark"/>
        </visual>
    </link>
    <joint name="c_clamp_motor_3" type="fixed">
        <parent link="c_clamp_3"/>
        <child link="motor_3"/>
    </joint>
    <link name="shaft_3">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <mesh filename="package://cara/models/motor_shaft.stl" scale="0.001 0.001 0.001"/>
            </geometry>
            <material name="plastic"/>
        </visual>
    </link>
    <joint name="motor_shaft_3" type="continuous">
        <parent link="base_link"/>
        <child link="shaft_3"/>
        <origin xyz="${(c_clamp_dist+0.01)} 0 0.045" rpy="0 0 0"/>
    </joint>
    <link name="wheel_3">
        <xacro:wheel/>
    </link>
    <joint name="shaft_wheel_3" type="fixed">
        <parent link="shaft_3"/>
        <child link="wheel_3"/>
    </joint>
    <!-- =======================================================Wheel 4====================================================================== -->
    <link name="c_clamp_4">
        <visual>
            <origin xyz="-0.05 ${-c_clamp_dist} 0.09" rpy="${pi/2} 0 ${pi/2}"/>
            <geometry>
                <mesh filename="package://cara/models/c_clamp.stl" scale="0.001 0.001 0.001"/>
            </geometry>
            <material name="aluminium"/>
        </visual>
    </link>
    <joint name="base_c_clamp_4" type="fixed">
        <parent link="base_link"/>
        <child link="c_clamp_4"/>
    </joint>
    <link name="motor_4">
        <visual>
            <origin xyz="0 ${-(c_clamp_dist-0.012)} 0.045" rpy="${pi/2} 0 ${pi}"/>
            <geometry>
                <mesh filename="package://cara/models/motor.stl" scale="0.001 0.001 0.001"/>
            </geometry>
            <material name="aluminium_dark"/>
        </visual>
    </link>
    <joint name="c_clamp_motor_4" type="fixed">
        <parent link="c_clamp_4"/>
        <child link="motor_4"/>
    </joint>
    <link name="shaft_4">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <mesh filename="package://cara/models/motor_shaft.stl" scale="0.001 0.001 0.001"/>
            </geometry>
            <material name="plastic"/>
        </visual>
    </link>
    <joint name="motor_shaft_4" type="continuous">
        <parent link="base_link"/>
        <child link="shaft_4"/>
        <origin xyz="0 ${-(c_clamp_dist+0.01)} 0.045" rpy="0 0 ${-pi/2}"/>
    </joint>
    <link name="wheel_4">
        <xacro:wheel/>
    </link>
    <joint name="shaft_wheel_4" type="fixed">
        <parent link="shaft_4"/>
        <child link="wheel_4"/>
    </joint>
    <!-- ======================================================= Top Plate ====================================================================== -->
    <link name="top_plate">
        <visual>
            <origin xyz="0.01 0 0.0836" rpy="${pi/2} 0 0"/>
            <geometry>
                <mesh filename="package://cara/models/top_plate.stl" scale="0.001 0.001 0.001"/>
            </geometry>
            <material name="blue"/>
        </visual>
    </link>
    <joint name="base_link_top_plate" type="fixed">
        <parent link="base_link"/>
        <child link="top_plate"/>
    </joint>
    <!-- ======================================================= Circuit Plate ====================================================================== -->
    <link name="circuit_plate">
        <visual>
            <origin xyz="0 0 0.093" rpy="${pi/2} 0 ${-5*pi/4}"/>
            <geometry>
                <mesh filename="package://cara/models/circuit_plate.stl" scale="0.001 0.001 0.001"/>
            </geometry>
            <material name="plastic"/>
        </visual>
    </link>
    <joint name="base_link_circuit_plate" type="fixed">
        <parent link="top_plate"/>
        <child link="circuit_plate"/>
    </joint>
    <!-- ======================================================= feedback ====================================================================== -->
    <link name="feedback">
        <visual>
            <origin xyz="0.063 0.1 -0.06" rpy="${pi/2} 0 ${pi/4}"/>
            <geometry>
                <mesh filename="package://cara/models/feedback.stl" scale="0.001 0.001 0.001"/>
            </geometry>
            <material name="aluminium_dark"/>
        </visual>
    </link>
    <joint name="base_link_feedback" type="fixed">
        <parent link="base_link"/>
        <child link="feedback"/>
    </joint>

    <xacro:stud myname="s1" x="0.073" y="0.06" z="0.006" parent="feedback"/>
    <xacro:stud myname="s2" x="-0.073" y="0.06" z="0.006" parent="feedback"/>
    <xacro:stud myname="s3" x="0.073" y="-0.06" z="0.006" parent="feedback"/>
    <xacro:stud myname="s4" x="-0.073" y="-0.06" z="0.006" parent="feedback"/>

    <xacro:stud myname="s5" x="0.06" y="0.0735" z="0.006" parent="feedback"/>
    <xacro:stud myname="s6" x="-0.06" y="0.0735" z="0.006" parent="feedback"/>
    <xacro:stud myname="s7" x="0.06" y="-0.0735" z="0.006" parent="feedback"/>
    <xacro:stud myname="s8" x="-0.06" y="-0.0735" z="0.006" parent="feedback"/>

    <!-- ======================================================= lidar Base ====================================================================== -->
    <link name="lidar_base">
        <visual>
            <origin xyz="0.01 0 0.1134" rpy="${pi/2} 0 0"/>
            <geometry>
                <mesh filename="package://cara/models/lidar_base.stl" scale="0.001 0.001 0.001"/>
            </geometry>
            <material name="transparent_acrylic_dark"/>
        </visual>
    </link>
    <joint name="circuit_plate_lidar_base" type="fixed">
        <parent link="circuit_plate"/>
        <child link="lidar_base"/>
    </joint>

    <xacro:stud myname="s9" x="-0.021" y="0.0321" z="0.098" parent="lidar_base"/>
    <xacro:stud myname="s10" x="0.041" y="0.0321" z="0.098" parent="lidar_base"/>
    <xacro:stud myname="s11" x="0.041" y="-0.0321" z="0.098" parent="lidar_base"/>
    <xacro:stud myname="s12" x="-0.021" y="-0.0321" z="0.098" parent="lidar_base"/>

    <!-- ======================================================= RPlidar ====================================================================== -->
    <link name="lidar_bottom">
        <visual>
            <origin xyz="0.0 0 0.161" rpy="${pi/2} 0 0"/>
            <geometry>
                <mesh filename="package://cara/models/lidar_bottom.stl" scale="0.001 0.001 0.001"/>
            </geometry>
            <material name="aluminium"/>
        </visual>
    </link>
    <joint name="lidar_base_lidar_bottom" type="fixed">
        <parent link="lidar_base"/>
        <child link="lidar_bottom"/>
    </joint>
    <link name="lidar_up">
        <visual>
            <origin xyz="0.0 0 0.158" rpy="${pi/2} 0 0"/>
            <geometry>
                <mesh filename="package://cara/models/lidar_up.stl" scale="0.001 0.001 0.001"/>
            </geometry>
            <material name="black_plastic"/>
        </visual>
    </link>
    <joint name="lidar_bottom_lidar_up" type="fixed">
        <parent link="lidar_bottom"/>
        <child link="lidar_up"/>
    </joint>

    <link name="rplidar_frame">
        <visual>
            <geometry>
                <sphere radius="0.001"/>
            </geometry>
            <material name="blue"/>
        </visual>
    </link>
    <joint name="base_link_rplidar_frame" type="fixed">
        <origin xyz="0.0 0 0.16" rpy="0 0 0"/>
        <parent link="base_link"/>
        <child link="rplidar_frame"/>
    </joint>
    <gazebo reference="rplidar_frame">
        <sensor type="ray" name="rplidar_sensor">
            <pose>0 0 0 0 0 0</pose>
            <visualize>true</visualize>
            <update_rate>8</update_rate>
            <ray>
                <scan>
                    <horizontal>
                        <samples>360</samples>
                        <resolution>1</resolution>
                        <min_angle>0</min_angle>
                        <max_angle>${pi*2}</max_angle>
                    </horizontal>
                </scan>
                <range>
                    <min>0.2</min>
                    <max>6.0</max>
                    <resolution>0.5</resolution>
                </range>
                <noise>
                    <type>gaussian</type>
                    <!-- Noise parameters based on published spec for Hokuyo laser
               achieving "+-30mm" accuracy at range < 10m.  A mean of 0.0m and
               stddev of 0.01m will put 99.7% of samples within 0.03m of the true
               reading. -->
                    <mean>0.0</mean>
                    <stddev>0.01</stddev>
                </noise>
            </ray>
            <plugin name="gazebo_ros_rplidar_controller" filename="libgazebo_ros_laser.so">
                <topicName>/cara/scan</topicName>
                <frameName>/rplidar_frame</frameName>
            </plugin>
        </sensor>
    </gazebo>
    <link name="x">
        <visual>
            <origin xyz="1.0 0 0" rpy="0 0 0"/>
            <geometry>
                <sphere radius="0.1"/>
            </geometry>
            <material name="blue"/>
        </visual>
    </link>
    <joint name="base_link_x" type="fixed">
        <parent link="base_link"/>
        <child link="x"/>
    </joint>
    <link name="y">
        <visual>
            <origin xyz="0 1 0" rpy="0 0 0"/>
            <geometry>
                <sphere radius="0.1"/>
            </geometry>
            <material name="bronze"/>
        </visual>
    </link>
    <joint name="base_link_y" type="fixed">
        <parent link="base_link"/>
        <child link="y"/>
    </joint>
    <link name="imu">
        <visual>
            <origin xyz="0.16 0.05 0.02" rpy="0 0 0"/>
            <geometry>
                <box size="0.05 0.03 0.004"/>
            </geometry>
            <material name="blue"/>
        </visual>
    </link>
    <joint name="base_link_imu" type="fixed">
        <parent link="base_link"/>
        <child link="imu"/>
    </joint>
</robot>
