# The joint state cotroller hadles publishing transforms for any moving joints
cara:
  # Publish all joint states
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  motor_and_wheelL_effort_controller:
    type: effort_controllers/JointEffortController
    joint: motor_and_wheelL
    publish_rate: 50
    pid: {p: 100.0, i: 0.01, d: 10.0}


  motor_and_wheelR_effort_controller:
      type: effort_controllers/JointEffortController
      joint: motor_and_wheelR
      publish_rate: 50
      pid: {p: 100.0, i: 0.01, d: 10.0}